### ISSUE TITLE
Alphabetical dependency sorting in project files is not alphabetical

### ISSUE THREAD

**Issue by miridius** [tengstrand/lein-polylith#17]
**Describe the bug**
I have the habit of always manually sorting dependencies alphabetically in my project.clj files, so I was suprised when `polylith sync` changed the order! It seems to happen when mixing single segment with multi segment dependencies, though I have not done much investigation other than to create the below reproducable example

**To Reproduce**
1. Create a new workspace with a namespace starting with a or b, and add a system + base to it:
```shell
$ lein polylith create w example base.namespace
$ cd example
$ lein polylith create s my-system my-base
```
2. Add [cheshire](https://github.com/dakrone/cheshire) as a dependency to the base by editing `bases/my-base/project.clj` as follows:
```clojure
(defproject base.namespace/my-base "0.1"
  :description "A my-base base."
  :dependencies [[base.namespace/interfaces "1.0"]
                 [cheshire "5.8.1"]
                 [org.clojure/clojure "1.9.0"]]
  :aot :all)
```
3. Ask polylith to sync the dependencies, thus triggering alphabetical sorting
```shell
$ lein polylith sync
updated: environments/development/project.clj
updated: bases/my-base/project.clj
updated: systems/my-system/project.clj
```
4. Open `bases/my-base/project.clj` again and observe that the deps are now out of order:
```clojure
(defproject base.namespace/my-base "0.1"
  :description "A my-base base."
  :dependencies [[cheshire "5.8.1"]
                 [base.namespace/interfaces "1.0"]
                 [org.clojure/clojure "1.9.0"]]
  :aot :all)
```
They are neither sorted by the first segment (since `base` should be before `cheshire`), nor by the last segment (since `clojure` should be before `namespace`), so I'm not really sure what is going on there.

**Expected behavior**
Dependencies are sorted alphabetically

**Operating System (please complete the following information):**
 - OS: Linux Mint
 - Version 19

**Versions (please complete the following information):**
 - Leiningen: 2.8.1
 - Java: 1.8.0_181
 - Polylith: 0.2.0 (also reproduceable on 0.1.1)

**Comment by furkan3ayraktar** [comment]
I agree on this, the dependencies should keep the alphabetical order. I have the same habit to keep dependencies in alphabetical order. 

I think this behavior is a result of [zprint](https://github.com/kkinnear/zprint) library. Can we do something about this or should we find another library to fix this issue @tengstrand ?

**Comment by tengstrand** [comment]
I have added an issue to zprint: 
https://github.com/kkinnear/zprint/issues/76
