### ISSUE TITLE
Template for Ring+Compojure

### ISSUE THREAD

**Issue by cybersapiens97** [tengstrand/lein-polylith#35]
**Is your feature request related to a problem? Please describe.**
No. But first, i've read the entire documentation and have seen the video that introduces Polylith and also messing up a bit with the RealWorld example. What i didn't saw anywhere was some comment about having to deal with Plugins, specifically the lein-ring plugin, which is needed to fire the ring server in an easy way. Took time to me realize that i had to put the plugin inside the project.clj of the entire development environment instead of my Base itself. Also i had some trouble having to refer to all libraries just to start a simple ring server + compojure, which i think it's a pretty standard thing that i use a lot to create new simple projects.

**Describe the solution you'd like**
First i'd like to see some kind of advice on the guide here at github, so people can be aware of plugins and where to put them. The second thing, if possible, some kind of template for polylith when dealing with Ring+Compojure, so i don't need to place all the libraries in the right places and the lein-ring plugin. I'm a beginner with backend and clojure tbh, and Polylith is helping me a lot, but took me hours just to create this simple template in order to start working with Ring+Compojure and a Ring server working.

**Describe alternatives you've considered**
I've considered creating a sample project so i can refer to it anytime. I understand that people have different ways of dealing with different projects, so no problem if this feature seems out of Polylith scope, it's just a suggestion.

**Comment by furkan3ayraktar** [comment]
Hi @cybersapiens97! The [RealWorld](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app) example has the ring+compojure setup already to show how Polylith can be used within that context. We are also considering to add or support templates for Polylith to help people easily start with common project patterns, but we haven't decided on this yet. 

If you create a repo with a simple Polylith+ring+compojure skeleton, I would like to include it in the Readme! Let me know how it goes!
