### ISSUE TITLE
Delete a base and a system

### ISSUE THREAD

**Issue by samirsa** [tengstrand/lein-polylith#39]
**Is your feature request related to a problem? Please describe.**
polylith is a great tool, but I think it is held by small issues such as the inability to delete a base and/or a system. Having this ability would greatly enable a more exploratory approach as we design a system and work towards packaging the different components into a new base/system. 

**Describe the solution you'd like**
Support for delete commands for base and system. 

**Describe alternatives you've considered**
I have tried moving the base and system which I do not want, but the polylith info command fails after that. It seems that a few links for api/documentation etc are still left in other parts of the directory structure, which might be causing this failure. 

I think that polylith is a great tool, but the inability to delete a base/system is a bit troublesome, as it goes against the whole philosophy of functional programing/clojure where you can try things quickly and interactively, and if they don't work out - then go back. With the inability to delete a base.system it seems as if we are stuck with a design architecture design that we took upfront. 

Alternatively, if you can guide what needs to be deleted - we can write a small script to do the same.

**Comment by tengstrand** [comment]
Hi! 
I'm glad to hear that you like the tool. 
I will have a look at this.
/Joakim

**Comment by tengstrand** [comment]
Let's say you create a project like this:
```
$ lein polylith create w example com.example
$ cd example
$ lein polylith create s system1 base1
$ lein polylith create c comp1
$ lein polylith add comp1 system1
```
If you want to delete 'system1' and 'base1', run these commands:
```
$ rm -rf bases/base1
$ rm -rf environments/development/docs/base1-readme.md
$ rm -rf environments/development/docs/system1-readme.md
$ rm -rf environments/development/project-files/bases/base1-project.clj
$ rm -rf environments/development/project-files/systems/system1-project.clj
$ rm -rf environments/development/resources/base1
$ rm -rf environments/development/src/com/example/base1
$ rm -rf environments/development/test/com/example/base1
$ rm -rf systems/system1
```
And if you have more than one environment, you need to delete files from all environments, not just 'development'.

Now run the 'info' command:
$ lein polylith info

...and it will show only the 'comp1' component, and not 'system1' and 'base1':
```
interfaces:
  comp1 *
components:
  comp1 *
bases:
systems:
environments:
  development
    comp1 *   -> component
```

**Comment by tengstrand** [comment]
We have implemented support for deletion of bases and systems now. You need to update the plugin version in project.clj from 0.2.2 to 0.2.3 in old workspaces to use the latest version.
