### ISSUE TITLE
Create new workspace does not correctly handle dashes for the folder names

### ISSUE THREAD

**Issue by mitchelkuijpers** [tengstrand/lein-polylith#42]
**Describe the bug**
If you create a workspace which has dashes in the namespace. Polylith will create some folders like `my-namespace` instead of the expected `my_namespace`.

**To Reproduce**
First create workspace with a namespace with dashes in it.
```
$ lein polylith create w my-namepsace my-namespace.with-dashes
```
If you step into the just created project and then try to add a system like this:

```
$ lein polylith create s rest-api rest-api
```
You will get the following warning:

```
Warning. Could not create symbolic link '/tmp/my-namespace/systems/rest-api/src/my_namespace/with_dashes/rest_api': /tmp/my-namespace/systems/rest-api/src/my_namespace/with_dashes/rest_api
Warning. Could not create symbolic link '/tmp/my-namespace/environments/development/src/my_namespace/with_dashes/rest_api': /tmp/my-namespace/environments/development/src/my_namespace/with_dashes/rest_api
Warning. Could not create symbolic link '/tmp/my-namespace/environments/development/test/my_namespace/with_dashes/rest_api': /tmp/my-namespace/environments/development/test/my_namespace/with_dashes/rest_api
```

**Expected behavior**
Polylith does the right transformation of replacing dashes by underscores while creating systems, bases and components but it creates the wrong folders on workspace setup. I expect it to also create the right folder on a creation of a workspace.

**Screenshots**
-

**Operating System (please complete the following information):**
 - OS: [Linux]
 - Version [5.7.2-arch1-1]

**Versions (please complete the following information):**
 - Leiningen: [2.9.3]
 - Java: [1.8.0_253]
 - Polylith: [2.3]

**Additional context**
-

**Comment by mitchelkuijpers** [comment]
Wow that was fast, thank you so much!

**Comment by tengstrand** [comment]
You are welcome! :-)
